# Generated by Django 4.2.16 on 2026-07-01 14:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='e.g. CSE, EEE, BBA', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='universities.university')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='e.g. BSC-CSE, MSC-IT', max_length=20)),
                ('degree_type', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='bachelor', max_length=20)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('total_credits', models.PositiveSmallIntegerField(default=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='academic.department')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'db_table': 'programmes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='e.g. Year 1, Level 1', max_length=100)),
                ('level_number', models.PositiveSmallIntegerField(help_text='1, 2, 3...')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='academic.programme')),
            ],
            options={
                'verbose_name': 'Academic Level',
                'verbose_name_plural': 'Academic Levels',
                'db_table': 'academic_levels',
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='e.g. Semester 1, Fall 2024', max_length=100)),
                ('semester_number', models.PositiveSmallIntegerField(help_text='1, 2, 3...')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.academiclevel')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semesters',
                'ordering': ['semester_number'],
                'indexes': [models.Index(fields=['is_current', 'is_active'], name='semesters_is_curr_b35984_idx')],
                'unique_together': {('academic_level', 'semester_number')},
            },
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['department', 'is_active'], name='programmes_departm_e799f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together={('department', 'code')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['university', 'is_active'], name='departments_univers_e5faa0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('university', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='academiclevel',
            unique_together={('programme', 'level_number')},
        ),
    ]
