# Generated by Django 4.2.16 on 2026-07-01 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_universities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'db_table': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UniversitySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_students', models.PositiveIntegerField(default=10000)),
                ('max_lecturers', models.PositiveIntegerField(default=500)),
                ('max_departments', models.PositiveIntegerField(default=50)),
                ('allow_ai_generation', models.BooleanField(default=True)),
                ('ai_questions_per_quiz', models.PositiveIntegerField(default=20)),
                ('ai_model_preference', models.CharField(default='gpt-4o', max_length=50)),
                ('allow_student_self_registration', models.BooleanField(default=False)),
                ('academic_year_start_month', models.PositiveSmallIntegerField(default=9, help_text='Month number (1=Jan, 9=Sep)')),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('grading_scale', models.JSONField(default=dict, help_text='e.g. {"A": 90, "B": 80, "C": 70, "D": 60, "F": 0}')),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('max_quiz_attempts', models.PositiveSmallIntegerField(default=1)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='universities.university')),
            ],
            options={
                'verbose_name': 'University Settings',
                'verbose_name_plural': 'University Settings',
                'db_table': 'university_settings',
            },
        ),
        migrations.CreateModel(
            name='UniversityAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_university_admins', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_admin_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University Admin',
                'verbose_name_plural': 'University Admins',
                'db_table': 'university_admins',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('university', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['slug'], name='universitie_slug_e6b1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['is_active', 'deleted_at'], name='universitie_is_acti_5bf273_idx'),
        ),
    ]
